In [3]:
import pandas as pd
import numpy as np
import networkx as nx
import random
import matplotlib.pyplot as plt
import datetime
from datetime import timedelta
from pulp import *
import pandas as pd
import joblib
import networkx as nx
import numpy as np
G = joblib.load('ALL_INDIA_GRAPH_STATION.pkl')
G.edges(data=True)
tt = pd.read_csv('ETA_LOADED_ENSEMBLE.csv')
tt = tt.drop(columns={'Unnamed: 0'})
tts = tt.mean(axis=1)
ids = pd.read_csv('segments_lko.csv')
ids['tt']=tts
ids['SG']=ids['SEGMENT'].str.split('-')

In [4]:
df_wagon_due_roh=joblib.load("df_wagon_due_roh.pkl")

In [5]:
df_wagon_under_maint=joblib.load("df_wagon_under_maint.pkl")
df_wagon_due_roh=df_wagon_due_roh[~df_wagon_due_roh.wagon_no.isin(df_wagon_under_maint.wagon_no)]
df_wagon_due_roh['wagon_var']=df_wagon_due_roh['wagon_no']+'_'+df_wagon_due_roh['wagon_type']+'_'+df_wagon_due_roh['ravsttn']
df_wagon_on_loc=df_wagon_due_roh.groupby(["ravsttn","wagon_type"])['wagon_no'].count()
df_wagon_on_loc=df_wagon_on_loc.reset_index()
df_wagon_curr_holding=joblib.load("df_wagon_curr_holding.pkl")
df_depo_capacity=joblib.load("df_depo_capacity.pkl")
df_wagon_type=joblib.load("df_wagon_type.pkl")
df_wagon_depo=joblib.load("df_wagon_depo.pkl")

In [6]:
df_wagon_type_comb=df_wagon_depo.merge(df_wagon_type, how='cross')
df_wagon_comb_type_ava=joblib.load("df_wagon_comb_type_ava.pkl")
df_wagon_type_comb['workdepot_wagon_type']='('+df_wagon_type_comb['depot']+','+df_wagon_type_comb['wagon_type']+')'
df_wagon_type_comb['present'] = df_wagon_type_comb['workdepot_wagon_type'].isin(df_wagon_comb_type_ava['workdepot_wagon_type'])
df_wagon_type_comb["present"] = df_wagon_type_comb["present"].astype(int)
df_wagon_type_comb=df_wagon_type_comb.reset_index(drop=True)
df_wagon_type_comb.head()
wagon_handled=df_wagon_type_comb.groupby('depot')[['wagon_type','present',]].apply(lambda x: x.set_index('wagon_type').to_dict(orient='index')).to_dict()

In [7]:
vars=LpVariable.dicts("var",(df_wagon_due_roh['wagon_var'].values,df_wagon_type_comb['depot'].unique()),cat='Binary')
prob = LpProblem("Minimize wagon time to reach workdepot", LpMinimize)
wgn_workdepot = [(w, b) for w in  df_wagon_due_roh['wagon_var'].values for b in df_wagon_type_comb['depot'].unique()]

C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pulp\pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

In [8]:
wgn_workdepot = [(w, b) for w in  df_wagon_due_roh['wagon_var'].values for b in df_wagon_type_comb['depot'].unique()]
df_final=pd.DataFrame()
for j in df_wagon_type_comb['depot'].unique():
    df=pd.DataFrame()
    wrk_shp_locn=j[:len(j)-2]
    cost=[]
    for i in df_wagon_due_roh['ravsttn'].unique():
        try:
            t=nx.shortest_path_length(G, source=i, target=wrk_shp_locn,weight='TRAVELTIME')
            cost.append(t)
        except:
            if(len(cost)==0):
                cost.append(0)
            else:
                cost.append(max(cost))
    df['ravsttn']=df_wagon_due_roh['ravsttn'].unique()
    df['cost']=pd.DataFrame(cost)
    df['workdepot']=j
    df_final=pd.concat(([df_final,df]))

In [9]:
df_final.head()

  ravsttn  cost workdepot
0      FN    21   ADTPFD
1    MBPJ    35   ADTPFD
2    GOSG    35   ADTPFD
3    CSCP    12   ADTPFD
4    BSCS    12   ADTPFD

In [10]:
df_cost=pd.merge(df_wagon_due_roh,df_final,how='inner')
df_cost=df_cost[['wagon_var','workdepot','cost']]
df_cost['cost'].replace(to_replace = 0, value = df_cost['cost'].mean(), inplace=True)
df = df_cost.groupby('wagon_var')[['workdepot','cost']].apply(lambda x: x.set_index('workdepot').to_dict(orient='index')).to_dict()
costs=df

C:\Users\Acer\AppData\Local\Temp\ipykernel_7080\3789995790.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cost['cost'].replace(to_replace = 0, value = df_cost['cost'].mean(), inplace=True)

In [11]:
prob += (
    lpSum([vars[w][b] * costs[w][b]['cost'] for (w, b) in wgn_workdepot]),
    "Sum_of_wagon_Transporting_Costs",)
Workdepot_capcity=df_depo_capacity.set_index('depot').to_dict('dict')
Workdepot_capcity=Workdepot_capcity['depot_capacity']
Current_wagon_load_wordepot=df_wagon_curr_holding.set_index('depot').to_dict()
Current_wagon_load_wordepot=Current_wagon_load_wordepot['current_holding']
for w in df_wagon_due_roh['wagon_var'].values:
    for b in df_wagon_type_comb['depot'].unique():
        prob+= (
            (vars[w][b]) <= 1,
            "Variable_can_be_either_zero_or_one"+str(vars[w][b])+"%s" % w,
    )

In [12]:
for b in df_wagon_type_comb['depot'].unique():
    try:
        prob += (
            lpSum([vars[w][b]  for w in df_wagon_due_roh['wagon_var'].values]) == max(Workdepot_capcity[b]-Current_wagon_load_wordepot[b],0),
            "Sum_of_wagons_assigned_should_be_less_than_capacity"+"%s" % b,)   
    except:
        prob += (
            lpSum([vars[w][b]  for w in df_wagon_due_roh['wagon_var'].values]) == max(Workdepot_capcity[b]-0,0),
            "Sum_of_wagons_assigned_should_be_less_than_capacity"+"%s" % b,)

In [13]:
for w in df_wagon_due_roh['wagon_var'].values:
    df_wagon_type=df_wagon_due_roh[df_wagon_due_roh['wagon_var']==w]
    df_wagon_type=df_wagon_type.reset_index(drop=True)
    type=df_wagon_type['wagon_type'][0]
    for b in df_wagon_type_comb['depot'].unique():
        try:
            handled=wagon_handled[b][type]['present']
        except:
            handled=0
        try:
            prob+= (
            (vars[w][b]) <= handled,
            "wagon_handled_current_either_zero_or_one"+str(b)+"%s" % w,
    )
        except:
            prob+= (
            (vars[w][b]) <= handled,
            "wagon_handled_current_either_zero_or_one"+str(b)+"%s" % w,
    )

In [14]:
wagon_locn_dict=df_wagon_on_loc.groupby('ravsttn')[['wagon_type','wagon_no',]].apply(lambda x: x.set_index('wagon_type').to_dict(orient='index')).to_dict()
wagon_locn_dict   
location=df_wagon_on_loc['ravsttn'].unique()
for c in location:
    df_wagon_type=df_wagon_type[df_wagon_type['ravsttn']==c]
    for type in df_wagon_type['wagon_type'].unique():
        try:
            prob += (
            lpSum([vars[w][b]  for w in df_wagon_due_roh['wagon_var'].values if type in w if c in w for b in df_wagon_type_comb['depot'].unique()]) <= wagon_locn_dict[c][type]['wagon_no'],
            "Sum_of_wagons_assigned_should_be_less_than_capacity"+"%s" % c+type,
        )
        except:
            continue

In [15]:
print(prob.solve(),LpStatus[prob.status])

1 Optimal

In [16]:
counter=0
var=[]
for v in prob.variables():
      if (v.varValue!=0):
        counter=counter+1
        var.append(v.name)

In [17]:
vars_list_final=[]
for k in range(len(var)):
    vars_list=var[k].split('_')
    vars_list_final.append(vars_list)
df_result = pd.DataFrame(vars_list_final, columns =['var', 'wagon_number','wagon_type','Current_wagon_location','workdepot']) 
df_result.head()

   var wagon_number wagon_type Current_wagon_location  workdepot
0  var  10010101703     BOXNM1                   MBPJ  BMYREPFD
1  var  10039672635     BOXNM1                   OTPS     OBRFD
2  var  10068960260      MBOXN                    BNE      ETFD
3  var  10070660202     BOXNM1                    TPT     JTJFD
4  var  10079250497     BOXNM1                    CLX    NLPDFD

In [18]:
df_cost[['wagon_number','wagon_type','Current_wagon_location']] = df_cost['wagon_var'].str.split('_',expand=True)
df_cost.head()

,wagon_var,workdepot,cost,wagon_number,wagon_type,Current_wagon_location
0,00506_BTAP_FN,ADTPFD,21.000000,00506,BTAP,FN
1,00506_BTAP_FN,AQICDFD,23.171314,00506,BTAP,FN
2,00506_BTAP_FN,BADFD,10.000000,00506,BTAP,FN
3,00506_BTAP_FN,BIAEXYDFD,23.171314,00506,BTAP,FN
4,00506_BTAP_FN,BIAPPYDFD,23.171314,00506,BTAP,FN

In [19]:
df_matrix=pd.merge(df_result,df_cost,how='inner',on=['wagon_number','wagon_type','Current_wagon_location','workdepot'])

In [20]:
df_matrix

,var,wagon_number,wagon_type,Current_wagon_location,workdepot,wagon_var,cost
0,var,10010101703,BOXNM1,MBPJ,BMYREPFD,10010101703_BOXNM1_MBPJ,23.171314
1,var,10039672635,BOXNM1,OTPS,OBRFD,10039672635_BOXNM1_OTPS,1.000000
2,var,10068960260,MBOXN,BNE,ETFD,10068960260_MBOXN_BNE,3.000000
3,var,10070660202,BOXNM1,TPT,JTJFD,10070660202_BOXNM1_TPT,1.000000
4,var,10079250497,BOXNM1,CLX,NLPDFD,10079250497_BOXNM1_CLX,4.000000
5,var,10079666021,BOXNM1,MSCA,BPAFD,10079666021_BOXNM1_MSCA,2.000000
6,var,10079768985,BOXNM1,TPT,JTJFD,10079768985_BOXNM1_TPT,1.000000
7,var,10079961959,BOXNM1,SCRM,BPAFD,10079961959_BOXNM1_SCRM,2.000000
8,var,10080160037,BOXNM1,MSCA,BPAFD,10080160037_BOXNM1_MSCA,2.000000
9,var,10089700111,BOXNM1,OTPS,OBRFD,10089700111_BOXNM1_OTPS,1.000000
10,var,14160652917,BOXNLW,KGP,NMPFD,14160652917_BOXNLW_KGP,1.000000
11,var,21110975989,BOSTHSM1,KPPR,JTJFD,21110975989_BOSTHSM1_KPPR,1.000000
12,var,21140913371,BOSTHSM2,KPPR,JTJFD,21140913371_BOSTHSM2_KPPR,1.000000
13,var,21151167893,BOSTHSM1,KPPR,JTJFD,21151167893_BOSTHSM1_KPPR,1.000000
14,var,22122121777,BOXNHL25T,JSPK,BMYREPFD,22122121777_BOXNHL25T_JSPK,23.171314
15,var,22131362079,BOXNHL,TPT,JTJFD,22131362079_BOXNHL_TPT,1.000000
16,var,25099561584,BOXNRHS,BSDC,PTRUFD,25099561584_BOXNRHS_BSDC,1.000000
17,var,25099628522,BOXNR,PSPC,BMYREPFD,25099628522_BOXNR_PSPC,23.171314
18,var,30019460069,BCNAM1,KKQ,NMPFD,30019460069_BCNAM1_KKQ,1.000000
19,var,30019960910,BCNAM1,KKQ,NMPFD,30019960910_BCNAM1_KKQ,1.000000
20,var,30028961571,BCNM1,GOC,TPGYFD,30028961571_BCNM1_GOC,1.000000
21,var,30039860849,BCNAM1,IOSM,MNGTFD,30039860849_BCNAM1_IOSM,1.000000
22,var,30039860917,BCNAM1,JUH,ETFD,30039860917_BCNAM1_JUH,1.000000
23,var,30039961294,BCNAM1,IOSM,MNGTFD,30039961294_BCNAM1_IOSM,1.000000
24,var,30069660198,BCNAM1,PICN,NVUFD,30069660198_BCNAM1_PICN,1.000000
25,var,30069764735,BCNAM1,KGP,NMPFD,30069764735_BCNAM1_KGP,1.000000
26,var,30089661014,BCNAM1,PGU,BMYREPFD,30089661014_BCNAM1_PGU,23.171314
27,var,30099761674,BCNAM1,PICN,NVUFD,30099761674_BCNAM1_PICN,1.000000
28,var,30099764507,BCNAM1,SNAG,SNFFD,30099764507_BCNAM1_SNAG,1.000000
29,var,31022111092,BCNAHSM1,CFS,SNFFD,31022111092_BCNAHSM1_CFS,1.000000
30,var,31101910929,BCNAHSM1,SNAG,SNFFD,31101910929_BCNAHSM1_SNAG,1.000000
31,var,31101911704,BCNAHSM1,ZCS,VENFD,31101911704_BCNAHSM1_ZCS,3.000000
32,var,31140554894,BCNAHSM1,UBL,NVUFD,31140554894_BCNAHSM1_UBL,1.000000
33,var,31160423798,BCNAHSM1,NBQY,NBQFD,31160423798_BCNAHSM1_NBQY,1.000000
34,var,33121192712,BCNHL,KKQ,NMPFD,33121192712_BCNHL_KKQ,1.000000
35,var,40011810069,BTPN,SDM,ERMGFD,40011810069_BTPN_SDM,23.171314
36,var,40028956484,BTPN,ALB,HAPAFD,40028956484_BTPN_ALB,1.000000
37,var,40061910214,BTPN,ALB,HAPAFD,40061910214_BTPN_ALB,1.000000
38,var,54252113117,BLCSB,ICMB,MBFD,54252113117_BLCSB_ICMB,1.000000
39,var,54252114220,BLCSB,ICMB,MBFD,54252114220_BLCSB_ICMB,1.000000
40,var,54252114466,BLCSB,ICMB,MBFD,54252114466_BLCSB_ICMB,1.000000
41,var,55070061758,BRNA,KGP,NMPFD,55070061758_BRNA_KGP,1.000000
42,var,55070063677,BRNA,KGP,NMPFD,55070063677_BRNA_KGP,1.000000
43,var,55090077272,BRNA,RMU,MBFD,55090077272_BRNA_RMU,3.000000
44,var,56070510475,BRNAHS,RMU,MBFD,56070510475_BRNAHS_RMU,3.000000
45,var,56140449971,BRNAHS,RMU,MBFD,56140449971_BRNAHS_RMU,3.000000
46,var,56160872834,BRNAHS,KFPR,MBFD,56160872834_BRNAHS_KFPR,3.000000
47,var,62250528949,BLCBM,WFD,SGWFFD,62250528949_BLCBM_WFD,1.000000
48,var,86100856129,BVZI,AMG,LKOFD,86100856129_BVZI_AMG,1.000000
49,var,86100956058,BVZI,BRPN,NBQFD,86100956058_BVZI_BRPN,1.000000
50,var,86100993916,BVZI,KGP,NMPFD,86100993916_BVZI_KGP,1.000000
51,var,86160976096,BVZI,KJGY,SREFD,86160976096_BVZI_KJGY,1.000000
52,var,87012010395,BVCM,MYS,MNGTFD,87012010395_BVCM_MYS,1.000000
53,var,87122212559,BVCM,MRB,HPTFD,87122212559_BVCM_MRB,1.000000
54,var,87122213150,BVCM,SGBJ,ETFD,87122213150_BVCM_SGBJ,1.000000
55,var,87122214546,BVCM,PNWP,AQICDFD,87122214546_BVCM_PNWP,23.171314
56,var,87142110019,BVCM,GIN,HPTFD,87142110019_BVCM_GIN,1.000000
57,var,94031810882,BRN22.9,NPTY,NMPFD,94031810882_BRN22.9_NPTY,1.000000
58,var,94122212342,BRN22.9M1,KGP,NMPFD,94122212342_BRN22.9M1_KGP,1.000000
59,var,94141351923,BRN22.9,KKQ,NMPFD,94141351923_BRN22.9_KKQ,1.000000

In [21]:
sum_1=0
for i in df_wagon_type_comb['depot'].unique():
    try:
        sum_1=sum_1+max(Workdepot_capcity[i]-Current_wagon_load_wordepot[i],0)
    except:
        sum_1=sum_1+max(Workdepot_capcity[i]-0,0)
print(sum_1)

60

In [22]:
sum_2=0
for j in Current_wagon_load_wordepot:
    sum_2=sum_2+Current_wagon_load_wordepot[j]
print(sum_2)

865

In [23]:
sum_3=0
for j in Workdepot_capcity:
    sum_3=sum_3+Workdepot_capcity[j]
print(sum_3)

392